config/routes.rb
require 'sidekiq/web'
BusmonitorPlatform::Application.routes.draw do |map|
	mount Sidekiq::Web=>'/sidekiq'
	resource  :session
	match '/login' => "sessions#new", :as => "login" 
	match '/logout' => "sessions#destroy", :as => "logout"
	match 'home/test' => "home#test"
	match 'home/init' => "home#init"
	match 'home/get_personinfo' => "home#get_personinfo"
	match 'home/modify_personinfo'=>"home#modify_personinfo"
	match 'home/city'=>"home#city"
	match 'home/station'=>"home#station"
	match 'home/bus'=>"home#bus"
	match 'home/add_cityinfo'=>"home#add_cityinfo"
	match 'home/edit_cityinfo'=>"home#edit_cityinfo"
	match 'home/delete_cityinfo'=>"home#edit_cityinfo"
	match 'home/backup'=>"home#backup"
	match 'home/deploy'=>"home#deploy"
	match 'home/deployprogress'=>"home#deployprogress"
	match 'home/projectid'=>"home#projectid"
	match 'home/allprojectid'=>"home#allprojectid"

   root :to => "home#init"

   match ':controller(/:action(/:id(.:format)))', :via => :all
	match '*a', :to=>'sessions#routeerror'
end

app/views/layouts/_footer.html.erb
<% if false %>
<div id="system_info"> 
        <%=  image_tag("next.gif", :border=>0) %>当前操作系统： <span id="platform"></span>&nbsp;&nbsp;&nbsp;&nbsp;
        浏览器： <span id="broswer"></span>&nbsp;&nbsp;&nbsp;&nbsp;
</div>
<% end %>
<div id="system_info"> 
        <%=  image_tag("next.gif", :border=>0) %>&nbsp;&nbsp;管理： 治安大队&nbsp;&nbsp;&nbsp;&nbsp;技术支持： 网警大队
        &nbsp;&nbsp;&nbsp;&nbsp;All Rights Reserved
<span id="time"></span>
</div>

app/views/layouts/_header.html.erb
<% if false %>
<audio id="player" controls="true" src="http://mp3.wooeu.com/mp3.php/15314202/mp3wooeu.mp3">你的浏览器太烂了，请更换浏览器先。</audio>
<div id="login-info">
  <span id="result"></span>
   &nbsp;&nbsp;&nbsp;&nbsp;
  <span>欢迎您，<%= User.find(session[:user_id]).username %></span>
  <span class="color-gray">|</span>
<%= link_to t('sign_out'),logout_path %>
</div>
<% end %>
<div id="first-line">
<ul>
<li><div class="a10"><img src="../images/main_12.jpg" alt=""></div></li>
<li><%= link_to image_tag("../images/main_17.jpg", :border=>0, :class => 'a1'), 
logout_path %></li>
<li><%= link_to image_tag("main_18.jpg", :border=>0, :class => 'a2'), 
test_path(:format=>:js), :remote=>true %></li>
<li><%= link_to image_tag("../images/main_19.jpg", :border=>0, :class => 'a3'), 
init_path(:format=>:js), :remote=>true %></li>
<li><div id="combine"><div id="nav_l"></div><div id="combine_in"><%=  image_tag("main_20.jpg", :border=>0, :class => 'a4') %><div id="info">用户: 小王</div><div id="info">所属单位: 派出所</div></div><div id="nav_r"></div></div></li>
</ul>
</div>
<div id="menu">
<ul>
<li><%= link_to "我的桌面", init_path(:format=>:js), :remote=>true %></li>
<li><%= link_to "新增人员", test_path(:format=>:js), :remote=>true %></li>
<li><a href="#">人员列表</a></li>
<li><a href="#">征兵联审</a></li>
<li><a href="#">统计分析</a></li>
<li><a href="#">用户管理</a></li>
<li><a href="#">部门管理</a></li>
<li><a href="#">帮助中心</a></li>
</ul>
</div>

app/views/layouts/_menu.html.erb
<ul>
<li id="city-management" class="left-menu">
     			<%= link_to home_city_path do %>
                <div><%= image_tag("citymenu.png", :class=>'menu-icon') %></div>
                <div class="menu-text"><%= t('city management') %></div>
       <% end %>
		<% if false %>
		<%= link_to home_projectid_path do %>
                <div><%= image_tag("projectidmenu.png", :class=>'menu-icon') %></div>
                <div class="menu-text"><%= t('projectid management') %></div>
       <% end %>
		<% end %>
</li>
<li id="station-management" class="left-menu">
     			<%= link_to home_station_path do %>
                <div><%= image_tag("stationmenu.png", :class=>'menu-icon') %></div>
                <div class="menu-text"><%= t('station management') %></div>
       <% end %>
</li>
<li id="car-management" class="left-menu">
        <%= link_to home_bus_path do %>
                <div><%= image_tag("busmenu.png", :class=>'menu-icon') %></div>
                <div class="menu-text"><%= t('car management') %></div>
        <% end %>  
</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('busmonitor_platform') %></title>
  <%= stylesheet_link_tag "extjsmsgbox.css","extjs-default.css","application.css","nprogress.css"%>
    <%= javascript_include_tag "ext-all", "jquery-1.4.3.min","ext-lang-zh_CN.js","application.js","extjsmsgbox.js","passwdstrength.js","time.js","nprogress.js",:cache => true  %>
  <%= csrf_meta_tag %>
</head>
<body onload=window_onload()>
<style>
.font-size40 { font-size:40px; }
.color-gray{ color: #DBCCDB}
.color-blue{ color: #15428B}
.color-red{ color: #CC0000}
.font-bold { font-weight:bold }
.font-size14 { font-size:14px; }
</style>
<script>
Ext.onReady(function(){
	var mainpanel =new Ext.create('Ext.panel.Panel', {
        width: 150,
        height: 150,
        border: false,
        frame: false,
        layout: 'fit',
//    	  bodyStyle: "background: #fff url('../images/bodys.jpg') no-repeat 0px 0px;background-position: 50% 90%;",
        html: '<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><div align="center" class="font-size40 font-bold color-blue">WiBUS系统联网运维平台</div>'
    });
    Ext.QuickTips.init();
     Ext.create('Ext.container.Viewport', {
            layout: 'border',
            items: [{
                region: 'north',
                border: false,
                height: 26,
                tbar: [ '<div style="color: #15428b; font-size:20px; font-weight:bold; font-family: Verdana,Arial,Helvetica,sans-serif !important;"><%= t('busmonitor_platform') %></div>',  '->','<div id="time" style="width: 190px; height: 16px;"><%= t('time loading') %><%= image_tag("loading.gif") %></div>','-', '<div><%= t('welcome') %><%= current_user.realname %></div>','-', {
                    text: '<%= t('personinfo management') %>',
                    iconCls: 'infomenu',
                    handler : function ( b, e ) {
						 		Ext.regModel('Sex', {
									fields: [{name: 'sex'},{name: 'value'}]
								});
								var SexStore = Ext.create('Ext.data.Store',{
									model : 'Sex',
									data : [
										{sex:'<%= t(:male) %>',value:'true'},
										{sex:'<%= t(:female) %>',value:'false'}
									]
								});
								Ext.Ajax.request({
				    				url: 'get_personinfo.json',
				    				params: { id : '<%= current_user.id %>' },
				    				success: function(response){
					       			var obj = Ext.decode(response.responseText); 
			                		if (obj.success) {
			                 			form.getForm().setValues({
								            id:obj.data['user'].id,
										   	username: obj.data['user'].username,
										   	realname: obj.data['user'].realname,
												email: obj.data['user'].email,
												phone: obj.data['user'].phone,
										    	sex: obj.data['user'].sex==true ? "true" : "false"
							        			});
											form.getForm().findField("username").setDisabled(true);
										//	form.getForm().findField("username").setReadOnly(true);
										//	form.getForm().findField("username").setFieldStyle("background: #d3d3d3");
			                    	} else {
			                     		Ext.MessageBox.alert("title",'false')
			                      					}
			              					},
		        					failure: function(response) {
		                			Ext.MessageBox.alert("<%= t('warn') %>","<%= t('network error') %>");
		               						}                	
	                 					});
                    	var form = new Ext.form.Panel({
					        width: 300,
					        frame: true,
					     //   title: '<%= t('personinfo management') %>',
					        bodyPadding: '0 0 0',
					        height: 300,
					        defaults: {
					            anchor: '100%',
					      //      allowBlank: false,
					            msgTarget: 'side',
					            labelWidth: 40
					       		 },
					        items: [
				        		{xtype:"hidden", name: "id", value: '<%= current_user.id %>'}, 
								{xtype:"textfield",fieldLabel: '<%= t('username') %>',name: "username"}, 
								{xtype:"textfield",fieldLabel: '<%= t('realname') %>',name: "realname"},  
								{
									xtype : 'combo',
									listConfig : {
										emptyText : '<%= t('no match value') %>', 
										maxHeight : 60 
									},
									name:'sex',
									autoSelect : true,
									fieldLabel:'<%= t('sex') %>',
									triggerAction: 'all',
									store : SexStore,
									displayField:'sex',
									valueField:'value',
									queryMode: 'local',
									forceSelection : true,
									typeAhead : true
								},   
								{xtype:"textfield",fieldLabel: '<%= t('phone') %>',name: "phone"},   
								{xtype:"textfield",fieldLabel: '<%= t('email') %>',name: "email", vtype: "email"}, 
								{
					            xtype:'fieldset',
					            title: '<%= t('password modify') %>',
					            collapsible: true,
					            defaultType: 'textfield',
					            layout: 'anchor',
					            defaults: {
					            	anchor: '100%',
										labelWidth: 48,
					            			},
					            items :[{
					                fieldLabel: '<%= t('new passwd') %>',
					                name: 'newpasswd',
										 xtype:'ux.passwordmeter'
					            			}]
					        		}],
					        buttonAlign:"center",
					        buttons: [
					           		 {
						            text: '<%= t(:save) %>',
						            handler: function(){
						            	var form = this.up('form').getForm();
						            	if(form.isValid()){
						                    form.submit({
						                        url: 'modify_personinfo.json',
						                        waitMsg: '<%= t('waiting') %>',
						                        success: function(fp, o) {																	edit_window.close()
					                        						},
														failure: function(fp, o) {			
							                       	form.reset(),										                 															edit_window.close()
					                        						}
					                    					});
					                				}
					            				}
				        			},{
						            text: '<%= t(:cancel) %>',
						            handler: function() { 
										edit_window.close()
						            }
						        }
				        	]
				        });
					    var edit_window = new Ext.Window({
					        width:240,
					        height:290,
					        resizable:false,
					        layout:"fit",
					        closeAction:'close',
					        plain: true,
					        constrainHeader: true,
					        modal:true,
							  title:"<%= t('personinfo management') %>",
            			  iconCls:"first",
					        bodyStyle: 'padding:5px;',
					        items:[form]
					    }).show();
                     }
                }, '-', {
                    	text: '<%= t('logout') %>',
                    	iconCls: 'logout',
                 		id: 'logout',
                  	animateTarget: 'logout',
                    	handler : function ( b, e ) {
                   		Ext.MessageBox.show({
                        	title:'<%= t('warn') %>',
                          	msg: '<%= t('are you sure logout') %>',
                         	closable: true,
                          	icon: Ext.MessageBox.QUESTION,
                         	animateTarget: 'logout',
                         	buttonText: {yes: "<%= t('confirm') %>", no: "<%= t('cancel') %>"},
                        	fn: function(btn){
                           	if(btn=='yes')
                              	Ext.Ajax.request({
                                 	url: "http://"+document.location.href.split('/')[2]+'/logout',
                                 	success: function(response, opts) {
                                  		window.location.href="http://"+document.location.href.split('/')[2]+'/login'
                                                           					},
                                  	failure: function(response, opts) {
                             				Ext.MessageBox.alert("<%= t('warn') %>","<%= t('network error') %>");
                                                           					}
                                                        				});
                                                    			}
                                                		});
                     				}
               					 }
					]
            				}, {
                	region: 'west',
                	collapsible: true,
                	split: true,
                	id: 'left',
                	title: '<%= t('menu') %>',
                	width: 150,
                	layout: 'accordion',
                	items: [{
                    contentEl: 'city-management',
                    title: '<%= t('city management') %>',
                    iconCls: 'cityicon',
                    autoScroll: true
               				 	},{
                    contentEl: 'station-management',
                    title:  '<%= t('station management') %>',
                    iconCls: 'stationicon', 
                    autoScroll: true
                				},  
                                		{
                    contentEl: 'car-management',
                    title: '<%= t('car management') %>',
                    iconCls: 'busicon',
                    autoScroll: true
               				 	},
                				],
           				 }, {
                	region: 'south',
                	height: 20,
						html: '<div style="margin: 0 auto; width: 300px;"><%=  image_tag("next.gif", :border=>0) %>&nbsp;&nbsp;Copyright &copy; 2010-2014 WiBUS All Rights Reserved</div>'            
            				}, {
                	region: 'center',
                	border:true,
                	layout:"fit",
                	id: 'center',
                	items: [     
	                	mainpanel
	              				 ]
            				}]
        		});

})
</script>
<% cache "layout" do %>
<div id="menu">
  <%= render :partial => "layouts/menu" %>
</div>
<% end %>
<div id="main">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><%= t('busmonitor_platform') %></title>
    <%= stylesheet_link_tag "login", :cache => true %>
  </head>
	<script language="JavaScript">
	var pc_table='<table width="820" align="center" border="0" cellpadding="0" cellspacing="0">'+
                        '<tr height="540">'+
                         '<td width="490"><img src="images/login/left_bg.jpg"/></td>'+
                         '<td valign="top">'+
                         '<br/><br/><br/><br/><br/>'+

                         '<%= form_tag session_path do %>'+
                         '<table cellpadding="10" cellspacing="15">'+
                           ' <tr align="left">'+
                           '<td colspan="2" class="font-size24 font-bold">WiBUS 用户登录</td>'+
                           '<% if flash[:notice] =~ /Invalid login/ %>'+
                           '<tr>'+
                              '<td class="font-size14 font-bold">登录错误 </td>'+
                           ' </tr>'+
                             '<% elsif flash[:notice] =~ /please log/ %>'+
                             '<tr>'+
                             '<td class="font-size14 font-bold">当前用户在其他地方登录,请重新登录 </td>'+
                             '</tr>'+
                             '<% elsif flash[:notice] =~ /user disable/ %>'+
                              '<tr>'+
                              '<td class="font-size14 font-bold">用户未激活 </td>'+
                              ' </tr>'+
                              '<% end %>'+
                              '</tr>'+
                            ' <tr>'+
                             '<td class="font-size14">用户名</td>'+
                              '<td><%= text_field_tag :username, params[:username],:class=>'login_input',:onblur=>'this.className="login_input"',:onfocus=>'this.className="login_input_focus"' %></td>'+
                             '</tr>'+
                              '<tr>'+
                              '<td class="font-size14">密码</td>'+
                               '<td><%= password_field_tag :password, params[:password],:class=>"login_input",:onblur=>'this.className="login_input"',:onfocus=>'this.className="login_input_focus"' %></td>'+
                               '</tr>'+
                                '<tr>'+
                                '<td></td>'+
                                 '<td><%= submit_tag "登录",:class=>"login_submit",:onmouseout=>'this.className="login_submit"', :onmouseover=>'this.className="login_submit_hover"'%></td>'+
                                 '</tr>'+
                                 '</table>'+
                                  '<% end %>'+


                               '</td>'+
                                 '</tr>'+
                                 '</table>'+
                              '<div id="login_footer">'+
                               '<div style="margin-top:8px;">'+
                                '<span>公司地址: 浙江省杭州市</span>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;'+
                                 '<span>联系电话: 400-888-8888</span>'+
                                 '</div>'+
                                  '<div style="margin-top:3px;">2010-2014 &copy; WiBUS 版权所有</div>'+
                                  '</div>'
         document.write(pc_table)
</script>
<body id="login_body">
</body>
</html>